
version: '3'
services:

  #PHP Service
  app:
    image: laraws/php:latest
    container_name: algorithm-php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/algorithm-php
    volumes:
      - ./:/var/algorithm-php
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini